server:
  port: 8091

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
    format:
      date: dd/MM/yyyy

  datasource:
    username: postgres
    password: alesya
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres


  flyway:
    enabled: true
    locations: classpath:db/migration

  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

